### ISSUE TITLE
delete /Path/to/template does not delete 

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-CLI#36] opened 2022-05-17 22:04 UTC
![image](https://user-images.githubusercontent.com/61938544/168917784-7aefaa5d-d2a7-40b3-8eea-6deb4fe680ae.png)

even after quitting / re-launching CLI.. object still appears. 

delete command should not return `sucess`if path is not absolute.

works if path is absolute..

**Comment by denizul** [comment] 2022-06-09 12:03
I wasn't able to reproduce this error, most likely you were using an outdated version of the CLI. We should discuss in the next meeting

**Comment by denizul** [comment] 2022-07-04 20:11
This was most likely due to the duplication issues we had resolved in our 1-1 meeting last week

**Closed by denizul** 2022-07-04 20:11 UTC
Labels: bug
